"use client";
import { useEffect,useState } from "react"; import Link from "next/link";
type Submission={id:string;projectName:string;url:string;category:string;description:string;githubUrl:string;status:string;verificationStatus:string;finalUrl:string;httpStatus:number;responseTimeMs:number;hosting:string;createdAt:string};
export default function AdminPage(){
 const [authed,setAuthed]=useState(false),[password,setPassword]=useState(""),[items,setItems]=useState<Submission[]>([]),[selected,setSelected]=useState<Submission|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function load(){const r=await fetch("/api/admin/submissions");if(r.ok){const d=await r.json();setItems(d.submissions);setAuthed(true)}else setAuthed(false)}
 useEffect(()=>{load()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(!r.ok){setError((await r.json()).message);return}setPassword("");await load()}
 async function decide(id:string,status:"approved"|"rejected"){setLoading(true);const r=await fetch("/api/admin/submissions/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)setError((await r.json()).message);else{setSelected(null);await load()}setLoading(false)}
 if(!authed)return <main><header className="nav shell"><Link href="/" className="brand">QINDEX<span>.</span></Link></header><section className="admin-login shell"><div className="eyebrow">PRIVATE ADMIN</div><h1>QIndex<br/><em>Review desk.</em></h1><form className="admin-login-form" onSubmit={login}><label>ADMIN PASSWORD</label><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your admin password"/>{error&&<div className="result error">{error}</div>}<button className="button">Enter admin →</button></form></section></main>;
 const pending=items.filter(x=>x.status==="pending");
 return <main><header className="nav shell"><Link href="/" className="brand">QINDEX<span>.</span></Link><nav><Link href="/">Public index</Link><button className="text-button" onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});setAuthed(false)}}>Sign out</button></nav></header>
 <section className="admin shell"><div className="admin-head"><div><div className="eyebrow">PRIVATE ADMIN</div><h1>Review desk.</h1><p>Review community submissions before they enter the public index.</p></div><div className="admin-count"><strong>{pending.length}</strong><span>pending</span></div></div>
 <div className="admin-layout"><div className="submission-list">{items.length===0?<div className="empty"><h3>No submissions yet.</h3><p>New community submissions will appear here.</p></div>:items.map(s=><button key={s.id} className={"submission-row "+(selected?.id===s.id?"selected":"")} onClick={()=>setSelected(s)}><span><strong>{s.projectName}</strong><small>{s.url}</small></span><span className={"admin-status "+s.status}>{s.status}</span></button>)}</div>
 {selected?<div className="submission-detail"><div className="eyebrow">{selected.status.toUpperCase()} · {selected.category}</div><h2>{selected.projectName}</h2><a className="admin-url" href={selected.url} target="_blank" rel="noreferrer">{selected.url} ↗</a><p>{selected.description||"No description supplied."}</p><div className="admin-facts"><div><span>HOSTING</span><strong>{selected.hosting||"Not detected"}</strong></div><div><span>HTTP</span><strong>{selected.httpStatus||"—"}</strong></div><div><span>RESPONSE</span><strong>{selected.responseTimeMs?selected.responseTimeMs+" ms":"—"}</strong></div><div><span>VERIFICATION</span><strong>{selected.verificationStatus}</strong></div></div>{selected.githubUrl&&<div className="detail-group"><label>GITHUB</label><a href={selected.githubUrl} target="_blank" rel="noreferrer">{selected.githubUrl} ↗</a></div>}<div className="admin-actions">{selected.status==="pending"&&<><button className="button" disabled={loading} onClick={()=>decide(selected.id,"approved")}>Approve & publish →</button><button className="button secondary" disabled={loading} onClick={()=>decide(selected.id,"rejected")}>Reject</button></>}</div></div>:<div className="submission-detail muted-detail"><span>Select a submission.</span></div>}</div></section></main>;
}