import Link from "next/link";import {notFound} from "next/navigation";
const projects:Record<string,{name:string;description:string;url:string;category:string;type:string;verified:boolean;status:string;tags:string[]}>={
"q-web":{name:"Q Web",description:"A public-facing example of a website served through the Quilibrium storage ecosystem.",url:"https://qweb.qstorage.quilibrium.com",category:"Infrastructure",type:"Website",verified:true,status:"Online",tags:["QStorage","Infrastructure"]},
"q-explorer":{name:"Q Explorer",description:"An ecosystem explorer concept for discovering public Quilibrium resources and projects.",url:"https://explorer.qstorage.quilibrium.com",category:"Tools",type:"Application",verified:true,status:"Online",tags:["QStorage","Explorer","Tools"]},
"q-docs":{name:"Q Docs",description:"Documentation and technical material for developers exploring Quilibrium.",url:"https://docs.quilibrium.com",category:"Developer",type:"Documentation",verified:false,status:"Online",tags:["Documentation","Developer"]}};
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects[slug];if(!p)notFound();return <main>
<header className="nav shell"><Link href="/" className="brand">QINDEX<span>.</span></Link><nav><Link href="/">Explore</Link><Link href="/submit">Submit</Link></nav></header>
<section className="project-hero shell"><Link href="/" className="back">← Back to index</Link><div className="project-labels">{p.verified&&<span className="verified large">✓ Verified</span>}<span>{p.type}</span><span>{p.category}</span></div><h1>{p.name}</h1><p>{p.description}</p><a className="button" href={p.url} target="_blank" rel="noreferrer">Visit project <span>↗</span></a></section>
<section className="shell project-layout"><div className="site-frame"><div className="frame-bar"><span>{p.url}</span><span>↗</span></div><div className="frame-placeholder"><span>PROJECT PREVIEW</span><strong>{p.name}</strong></div></div>
<aside className="details"><div className="detail-group"><label>STATUS</label><strong className="status-line"><i/> {p.status}</strong></div><div className="detail-group"><label>HOSTING</label><strong>{p.url.includes("qstorage.quilibrium.com")?"QStorage":"Quilibrium ecosystem"}</strong></div><div className="detail-group"><label>VERIFICATION</label><strong>{p.verified?"URL verified by QIndex":"Community submitted"}</strong></div><div className="detail-group"><label>TAGS</label><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></aside></section>
<section className="shell claim-box"><div><div className="eyebrow">PROJECT OWNERS</div><h2>Is this your project?</h2><p>Claiming is not enabled in v0.1 yet. The next release will let owners verify control of a listed website and manage its profile.</p></div><Link href="/submit" className="button secondary">Suggest an update</Link></section>
<footer className="shell footer"><span>QINDEX © 2026</span><span>Verification describes what QIndex can observe.</span></footer></main>}