import Link from "next/link";import {notFound} from "next/navigation";import {pool} from "@/lib/db";
export const runtime="nodejs";
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const r=await pool.query(`select slug,project_name as "name",description,url,category,verification_status as "verificationStatus",hosting from projects where slug=$1`,[slug]); const p=r.rows[0]; if(!p)notFound();
 const verified=p.verificationStatus==="qstorage";
 return <main><header className="nav shell"><Link href="/" className="brand">QINDEX<span>.</span></Link><nav><Link href="/">Explore</Link><Link href="/submit">Submit</Link></nav></header>
 <section className="project-hero shell"><Link href="/" className="back">← Back to index</Link><div className="project-labels">{verified&&<span className="verified large">✓ QStorage</span>}<span>Website</span><span>{p.category}</span></div><h1>{p.name}</h1><p>{p.description||"A publicly discoverable project indexed by QIndex."}</p><a className="button" href={p.url} target="_blank" rel="noreferrer">Visit project <span>↗</span></a></section>
 <section className="shell project-layout"><div className="site-frame"><div className="frame-bar"><span>{p.url}</span><span>↗</span></div><div className="frame-placeholder"><span>PROJECT PREVIEW</span><strong>{p.name}</strong></div></div>
 <aside className="details"><div className="detail-group"><label>STATUS</label><strong className="status-line"><i/> Indexed</strong></div><div className="detail-group"><label>HOSTING</label><strong>{p.hosting||"Not detected"}</strong></div><div className="detail-group"><label>VERIFICATION</label><strong>{verified?"QStorage hostname verified":"Reachability checked"}</strong></div><div className="detail-group"><label>CATEGORY</label><strong>{p.category}</strong></div></aside></section>
 <section className="shell claim-box"><div><div className="eyebrow">PROJECT OWNERS</div><h2>Is this your project?</h2><p>Owner claiming is not enabled yet. QIndex currently manages publication through community submission and review.</p></div><Link href="/submit" className="button secondary">Suggest an update</Link></section>
 <footer className="shell footer"><span>QINDEX © 2026</span><span>Verification describes what QIndex can observe.</span></footer></main>
}