"use client";
import {FormEvent,useState} from "react"; import Link from "next/link";
export default function SubmitPage(){
 const [url,setUrl]=useState("");const [result,setResult]=useState<any>(null);const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setResult(null);try{const r=await fetch("/api/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.message);setResult({ok:true,message:d.verified?"URL verified. Your project is ready for review.":"URL is reachable, but QIndex could not verify QStorage hosting.",details:[d.finalUrl&&"Resolved URL: "+d.finalUrl,d.status&&"HTTP status: "+d.status,d.responseTimeMs&&"Response time: "+d.responseTimeMs+" ms",d.hosting&&"Detected hosting: "+d.hosting].filter(Boolean)});}catch(e){setResult({ok:false,message:e instanceof Error?e.message:"Verification failed."})}finally{setLoading(false)}}
 return <main><header className="nav shell"><Link href="/" className="brand">QINDEX<span>.</span></Link><nav><Link href="/">Explore</Link><a href="#how">How it works</a></nav></header>
 <section className="submit-page shell"><Link href="/" className="back">← Back to index</Link><div className="eyebrow">COMMUNITY SUBMISSION</div><h1>Suggest a project<br/><em>for the index.</em></h1><p className="lead">Submit a publicly accessible website or project. QIndex checks the URL first, then the entry can be reviewed before publication.</p>
 <form className="submission-form" onSubmit={submit}><div className="field"><label>PROJECT URL <span>*</span></label><input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-project.qstorage.quilibrium.com"/><small>Use the public URL visitors can actually open.</small></div>
 <div className="form-grid"><div className="field"><label>PROJECT NAME</label><input placeholder="Project name"/></div><div className="field"><label>CATEGORY</label><select defaultValue="Other">{["Other","Infrastructure","Tools","Developer","AI","Finance","Gaming","Research"].map(x=><option key={x}>{x}</option>)}</select></div></div>
 <div className="field"><label>DESCRIPTION</label><textarea placeholder="What does this project do?" rows={5}/></div><div className="field"><label>GITHUB <span className="muted">(optional)</span></label><input placeholder="https://github.com/..."/></div>
 <div className="verify-note"><span>✓</span><p><strong>Verification first.</strong> Submitting a URL does not automatically publish it. QIndex checks reachability and visible hosting signals before the project enters review.</p></div>
 <button className="button submit-button" disabled={loading}>{loading?"Checking URL…":"Verify & submit →"}</button>
 {result&&<div className={result.ok?"result success":"result error"}><strong>{result.message}</strong>{result.details?.map((x:string)=><span key={x}>{x}</span>)}</div>}</form></section>
 <section className="submit-band" id="how"><div className="shell split"><div><div className="eyebrow">WHAT HAPPENS NEXT</div><h2>Verify.<br/>Review.<br/>Publish.</h2></div><div><p>QIndex separates technical verification from ownership. A reachable website can be verified technically, while publication and ownership remain separate review steps.</p></div></div></section>
 <footer className="shell footer"><span>QINDEX © 2026</span><span>Independent ecosystem directory</span></footer></main>;
}